@startuml BattleClasses

package GameManager {
    class GameManager {
        + Turn : int
    }

    class WarResult {

    }
}

package Param {
    '兵種
    enum WeaponryType {
        Infantry
        Bowman
        Cavalry
    }

    '兵種適正
    enum AptitudeType {
        A
        B
        C
    }

    '所属
    enum BelongType {
        Enemy
        Friend
    }

    '小隊
    class Platoon {
        + WarPlatoonId : int
        + Belong : BelongType
        + Soldiers : int
        + Weaponry : WeaponryType
        + Aptitude : AptitudeType
        + LeaderParam : LeaderParam
        + Speed : int
    }
}

package Calculator {
    class SpeedCalculator {
        +{static} SpeedCalculate(this Platoon,WaponryType,Aptitude,LeaderParam) : int
    }

    class DamageCalculator {
        +{static} DamageCalculate(this Platoon,Platoon) : Damage
    }

    class Damage {
        + EnemyPlatoonDamage : int
        + FriendPlatoonDamage : int
    }
}

package Command {
    class PlatoonCommand {
        + Attack()
        + Defence()
        + Tecihque()
        + Escape()
    }
}

package UI {

    class WarInfoView {

    }

    class PlatoonView {

    }
}
@enduml